Workaround for NPE in ChunkLightStorage.get()
This happens for some reason:

java.lang.NullPointerException: Cannot load from long array because "this.data" is null
 at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.chunk.ChunkLightStorage$LightSection.get(ChunkLightStorage.java:132)
 at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.chunk.ChunkLightStorage.get(ChunkLightStorage.java:71)
 at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.chunk.ChunkWrapper.getSkyLight(ChunkWrapper.java:368)
 at com.seibel.distanthorizons.core.dataObjects.transformers.LodDataBuilder.createChunkData(LodDataBuilder.java:103)
 at com.seibel.distanthorizons.core.dataObjects.transformers.ChunkToLodBuilder.tickThreadTask(ChunkToLodBuilder.java:161)
 at com.seibel.distanthorizons.core.dataObjects.transformers.ChunkToLodBuilder.lambda$tick$1(ChunkToLodBuilder.java:119)